#!/usr/bin/env bash

# Install the provided Nerd fonts for use in the terminal.
# Additional fonts may be downloaded from https://www.nerdfonts.com/ and added to the /fonts directory of this
# repository.
# Alternatively, fonts may be directly installed using a sparse checkout of https://github.com/ryanoasis/nerd-fonts.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$SCRIPT_DIR/colors"

# Variables
FONT_DIR="${PWD%/*}/fonts"
TARGET_DIR="$HOME/.local/share/fonts"

_help()
{
  echo "This scripts install Nerd fonts contained in the /fonts directory of this repository."
  echo ""
  echo
  echo "Syntax: install_nerd_font -[h]"
  echo "Options:"
  echo "  -h    Print this help"
  echo
}

#############################################################
# Checks existence of target directory and creates it if
# necessary.
# Globals:
#   TARGET_DIR
# Outputs:
#   Writes log output to stdout.
#############################################################
_check_target_dir_and_create()
{
  if [[ ! -d "$TARGET_DIR" ]]; then
    info "Target directory does not exist yet. Creating..."
    mkdir $TARGET_DIR
  fi
}

#############################################################
# Copies all Nerd fonts contained in the repository to the
# target directory.
# Globals:
#   FONT_DIR
#   TARGET_DIR
# Outputs:
#   Writes log output to stdout.
#############################################################
_copy_fonts()
{
  for dir in "$FONT_DIR"/*; do
    if [ -d "$dir" ] && [ "$dir" != "." ] && [ "$dir" != ".." ]; then
      info "Copy directory: $dir"
      cp -r "$dir" "$TARGET_DIR"
    fi
  done
}

#############################################################
# Updates the font cache.
# Outputs:
#   Writes log output to stdout.
#############################################################
_update_font_cache()
{
  info "Update font cache"
  fc-cache -f -v
}

main()
{
  info "Installing fonts from $FONT_DIR"
  info "Configured target directory (user install): $TARGET_DIR"

  _check_target_dir_and_create
  _copy_fonts
  _update_font_cache
}

main "@"
